# Generated by Django 5.2.8 on 2025-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JavaScript')], max_length=10)),
                ('content', models.TextField()),
                ('sample_html', models.TextField(blank=True)),
                ('sample_css', models.TextField(blank=True)),
                ('sample_js', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
